# Generated by Django 4.1.7 on 2023-04-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depatment',
            new_name='Department',
        ),
    ]
