# Generated by Django 4.1.7 on 2023-04-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_of_game_games_gamen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='playern',
            new_name='playerna',
        ),
        migrations.AlterField(
            model_name='player',
            name='playern',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
